delete from ALM_WORKFLOW t where t.wf_item_id>700 and t.wf_item_id<800;


insert into ALM_WORKFLOW (WF_ITEM_ID, TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_TYPE, VERSION, PHASE_ID, PHASE_NAME, VM_TASK_NAME, VM_LINK_ID, VM_TASK_NO, LINK_ID, LINK_NO, LINK_NO_TYPE, ROLE_CODE, LINK_URL, NEXT_LINK_COND_TREE, IS_DISPLAY, IS_ROLE, IS_PRINT, IS_REAUTHORIZE, IS_TERMINATE, IS_BACK, IS_NOTICE, IS_DISCUSS, BACK_COND, BACK_LINK_NO, HTML_TAG_NAME, HTML_TAG_DESC, INIT_LINK_NO, INIT_LINK_ID, NEED_INIT_STAFF, CREATE_STAFF_ID, CREATE_TIME, START_TIME, END_TIME, VALID_TAG, IS_COMPANY, IS_DEPART, IS_GROUP, CONNECT_POINT)
values (701, 50000, 'com.asiainfo.aiga.workflow.testEAESubWF', 1, null, '1', '创建', '创建端到端测试', 701, 'createEAESubTaskTest', 701, 'createEAESubTaskTest', 'mgr', 'WF_TEST_CHD', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into ALM_WORKFLOW (WF_ITEM_ID, TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_TYPE, VERSION, PHASE_ID, PHASE_NAME, VM_TASK_NAME, VM_LINK_ID, VM_TASK_NO, LINK_ID, LINK_NO, LINK_NO_TYPE, ROLE_CODE, LINK_URL, NEXT_LINK_COND_TREE, IS_DISPLAY, IS_ROLE, IS_PRINT, IS_REAUTHORIZE, IS_TERMINATE, IS_BACK, IS_NOTICE, IS_DISCUSS, BACK_COND, BACK_LINK_NO, HTML_TAG_NAME, HTML_TAG_DESC, INIT_LINK_NO, INIT_LINK_ID, NEED_INIT_STAFF, CREATE_STAFF_ID, CREATE_TIME, START_TIME, END_TIME, VALID_TAG, IS_COMPANY, IS_DEPART, IS_GROUP, CONNECT_POINT)
values (702, 50000, 'com.asiainfo.aiga.workflow.testEAESubWF', 1, null, '2', '分析', '需求分析', 702, 'eaeSubTaskTestAys', 702, 'eaeSubTaskTestAys', 'user', 'WF_TEST_PFR', '/aiga/workflow/eAESubTaskTest/EaeSubTaskTestAys.jsp', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into ALM_WORKFLOW (WF_ITEM_ID, TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_TYPE, VERSION, PHASE_ID, PHASE_NAME, VM_TASK_NAME, VM_LINK_ID, VM_TASK_NO, LINK_ID, LINK_NO, LINK_NO_TYPE, ROLE_CODE, LINK_URL, NEXT_LINK_COND_TREE, IS_DISPLAY, IS_ROLE, IS_PRINT, IS_REAUTHORIZE, IS_TERMINATE, IS_BACK, IS_NOTICE, IS_DISCUSS, BACK_COND, BACK_LINK_NO, HTML_TAG_NAME, HTML_TAG_DESC, INIT_LINK_NO, INIT_LINK_ID, NEED_INIT_STAFF, CREATE_STAFF_ID, CREATE_TIME, START_TIME, END_TIME, VALID_TAG, IS_COMPANY, IS_DEPART, IS_GROUP, CONNECT_POINT)
values (703, 50000, 'com.asiainfo.aiga.workflow.testEAESubWF', 1, null, '3', '设计', '测试设计', 703, 'eaeSubTaskTestDsgn', 703, 'eaeSubTaskTestDsgn', 'user', 'WF_TEST_PFR', '/aiga/workflow/eAESubTaskTest/EaeSubTaskTestDsgn.jsp', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into ALM_WORKFLOW (WF_ITEM_ID, TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_TYPE, VERSION, PHASE_ID, PHASE_NAME, VM_TASK_NAME, VM_LINK_ID, VM_TASK_NO, LINK_ID, LINK_NO, LINK_NO_TYPE, ROLE_CODE, LINK_URL, NEXT_LINK_COND_TREE, IS_DISPLAY, IS_ROLE, IS_PRINT, IS_REAUTHORIZE, IS_TERMINATE, IS_BACK, IS_NOTICE, IS_DISCUSS, BACK_COND, BACK_LINK_NO, HTML_TAG_NAME, HTML_TAG_DESC, INIT_LINK_NO, INIT_LINK_ID, NEED_INIT_STAFF, CREATE_STAFF_ID, CREATE_TIME, START_TIME, END_TIME, VALID_TAG, IS_COMPANY, IS_DEPART, IS_GROUP, CONNECT_POINT)
values (704, 50000, 'com.asiainfo.aiga.workflow.testEAESubWF', 1, null, '4', '审核', '测试审核', 704, 'eaeSubTaskTestVerify', 704, 'eaeSubTaskTestVerify', 'user', 'WF_TEST_CHD', '/aiga/workflow/eAESubTaskTest/EaeSubTaskTestVerify.jsp', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into ALM_WORKFLOW (WF_ITEM_ID, TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_TYPE, VERSION, PHASE_ID, PHASE_NAME, VM_TASK_NAME, VM_LINK_ID, VM_TASK_NO, LINK_ID, LINK_NO, LINK_NO_TYPE, ROLE_CODE, LINK_URL, NEXT_LINK_COND_TREE, IS_DISPLAY, IS_ROLE, IS_PRINT, IS_REAUTHORIZE, IS_TERMINATE, IS_BACK, IS_NOTICE, IS_DISCUSS, BACK_COND, BACK_LINK_NO, HTML_TAG_NAME, HTML_TAG_DESC, INIT_LINK_NO, INIT_LINK_ID, NEED_INIT_STAFF, CREATE_STAFF_ID, CREATE_TIME, START_TIME, END_TIME, VALID_TAG, IS_COMPANY, IS_DEPART, IS_GROUP, CONNECT_POINT)
values (705, 50000, 'com.asiainfo.aiga.workflow.testEAESubWF', 1, null, '5', '准生产测试', '上线前环境测试', 705, 'eaeSubTaskTestQuaRel', 705, 'eaeSubTaskTestQuaRel', 'user', 'WF_TEST_PFR', '/aiga/workflow/eAESubTaskTest/EaeSubTaskTestQuaRel.jsp', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into ALM_WORKFLOW (WF_ITEM_ID, TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_TYPE, VERSION, PHASE_ID, PHASE_NAME, VM_TASK_NAME, VM_LINK_ID, VM_TASK_NO, LINK_ID, LINK_NO, LINK_NO_TYPE, ROLE_CODE, LINK_URL, NEXT_LINK_COND_TREE, IS_DISPLAY, IS_ROLE, IS_PRINT, IS_REAUTHORIZE, IS_TERMINATE, IS_BACK, IS_NOTICE, IS_DISCUSS, BACK_COND, BACK_LINK_NO, HTML_TAG_NAME, HTML_TAG_DESC, INIT_LINK_NO, INIT_LINK_ID, NEED_INIT_STAFF, CREATE_STAFF_ID, CREATE_TIME, START_TIME, END_TIME, VALID_TAG, IS_COMPANY, IS_DEPART, IS_GROUP, CONNECT_POINT)
values (706, 50000, 'com.asiainfo.aiga.workflow.testEAESubWF', 1, null, '6', '生产测试', '生产测试', 706, 'eaeSubTaskTestProduce', 706, 'eaeSubTaskTestProduce', 'user', 'WF_TEST_PFR', '/aiga/workflow/eAESubTaskTest/EaeSubTaskTestProduce.jsp', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into ALM_WORKFLOW (WF_ITEM_ID, TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_TYPE, VERSION, PHASE_ID, PHASE_NAME, VM_TASK_NAME, VM_LINK_ID, VM_TASK_NO, LINK_ID, LINK_NO, LINK_NO_TYPE, ROLE_CODE, LINK_URL, NEXT_LINK_COND_TREE, IS_DISPLAY, IS_ROLE, IS_PRINT, IS_REAUTHORIZE, IS_TERMINATE, IS_BACK, IS_NOTICE, IS_DISCUSS, BACK_COND, BACK_LINK_NO, HTML_TAG_NAME, HTML_TAG_DESC, INIT_LINK_NO, INIT_LINK_ID, NEED_INIT_STAFF, CREATE_STAFF_ID, CREATE_TIME, START_TIME, END_TIME, VALID_TAG, IS_COMPANY, IS_DEPART, IS_GROUP, CONNECT_POINT)
values (707, 50000, 'com.asiainfo.aiga.workflow.testEAESubWF', 1, null, '8', '功能测试', '功能测试', 707, 'eaeSubTaskTestFunc', 707, 'eaeSubTaskTestFunc', 'user', 'WF_TEST_PFR', '/aiga/workflow/eAESubTaskTest/EaeSubTaskTestFunc.jsp', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into ALM_WORKFLOW (WF_ITEM_ID, TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_TYPE, VERSION, PHASE_ID, PHASE_NAME, VM_TASK_NAME, VM_LINK_ID, VM_TASK_NO, LINK_ID, LINK_NO, LINK_NO_TYPE, ROLE_CODE, LINK_URL, NEXT_LINK_COND_TREE, IS_DISPLAY, IS_ROLE, IS_PRINT, IS_REAUTHORIZE, IS_TERMINATE, IS_BACK, IS_NOTICE, IS_DISCUSS, BACK_COND, BACK_LINK_NO, HTML_TAG_NAME, HTML_TAG_DESC, INIT_LINK_NO, INIT_LINK_ID, NEED_INIT_STAFF, CREATE_STAFF_ID, CREATE_TIME, START_TIME, END_TIME, VALID_TAG, IS_COMPANY, IS_DEPART, IS_GROUP, CONNECT_POINT)
values (708, 50000, 'com.asiainfo.aiga.workflow.testEAESubWF', 1, null, '5', '准生产测试', '上线前环境测试审核', 708, 'eaeSubTaskTestBTVerify', 708, 'eaeSubTaskTestBTVerify', 'user', 'WF_TEST_CHD', '/aiga/workflow/eAESubTaskTest/EaeSubTaskTestBTVerify.jsp', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into ALM_WORKFLOW (WF_ITEM_ID, TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_TYPE, VERSION, PHASE_ID, PHASE_NAME, VM_TASK_NAME, VM_LINK_ID, VM_TASK_NO, LINK_ID, LINK_NO, LINK_NO_TYPE, ROLE_CODE, LINK_URL, NEXT_LINK_COND_TREE, IS_DISPLAY, IS_ROLE, IS_PRINT, IS_REAUTHORIZE, IS_TERMINATE, IS_BACK, IS_NOTICE, IS_DISCUSS, BACK_COND, BACK_LINK_NO, HTML_TAG_NAME, HTML_TAG_DESC, INIT_LINK_NO, INIT_LINK_ID, NEED_INIT_STAFF, CREATE_STAFF_ID, CREATE_TIME, START_TIME, END_TIME, VALID_TAG, IS_COMPANY, IS_DEPART, IS_GROUP, CONNECT_POINT)
values (709, 50000, 'com.asiainfo.aiga.workflow.testEAESubWF', 1, null, '6', '生产测试', '生产测试审核', 709, 'eaeSubTaskTestOnlineVerify', 709, 'eaeSubTaskTestOnlineVerify', 'user', 'WF_TEST_CHD', '/aiga/workflow/eAESubTaskTest/EaeSubTaskTestOnlineVerify.jsp', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into ALM_WORKFLOW (WF_ITEM_ID, TEMPLATE_ID, TEMPLATE_NAME, TEMPLATE_TYPE, VERSION, PHASE_ID, PHASE_NAME, VM_TASK_NAME, VM_LINK_ID, VM_TASK_NO, LINK_ID, LINK_NO, LINK_NO_TYPE, ROLE_CODE, LINK_URL, NEXT_LINK_COND_TREE, IS_DISPLAY, IS_ROLE, IS_PRINT, IS_REAUTHORIZE, IS_TERMINATE, IS_BACK, IS_NOTICE, IS_DISCUSS, BACK_COND, BACK_LINK_NO, HTML_TAG_NAME, HTML_TAG_DESC, INIT_LINK_NO, INIT_LINK_ID, NEED_INIT_STAFF, CREATE_STAFF_ID, CREATE_TIME, START_TIME, END_TIME, VALID_TAG, IS_COMPANY, IS_DEPART, IS_GROUP, CONNECT_POINT)
values (799, 50000, 'com.asiainfo.aiga.workflow.testEAESubWF', 1, null, '99', '结束', '端到端测试结束', 799, 'eaeSubTaskTestEnd', 799, 'eaeSubTaskTestEnd', 'end', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

