insert into sys_id_generator (TABLE_NAME, DOMAIN_ID, GENERATOR_TYPE, SEQUENCE_NAME, MAX_ID, START_VALUE, MIN_VALUE, MAX_VALUE, INCREMENT_VALUE, CYCLE_FLAG, CACHE_SIZE, SEQUENCE_CREATE_SCRIPT, HIS_TABLE_NAME, HIS_SEQUENCE_NAME, HIS_DATA_FLAG, HIS_MAX_ID, HIS_DONECODE_FLAG, SKIP_TYPE, DEAL_CLASS)
values ('AIGA_TESTTASK_CHANGE', 11, 'S', 'AIGA_TESTTASK_CHANGE$SEQ', null, null, null, null, 1, 'N', 20, '', '', '', '', null, '', null, '');

